version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:HelloWorld@007@db:5432/mydb
    depends_on:
      - db
    volumes:
      - ./server:/home/backend
    command: sh -c "npx prisma migrate dev && npm run seed && npm run dev"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/home/frontend
    command: ["npm", "run", "dev"]

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: HelloWorld@007
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
