services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:HelloWorld@007@db:5432/mydb
      - PORT=8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/home/backend
    command: sh -c "npx prisma migrate dev && npm run seed && npm run dev"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/
    depends_on:
      - backend
    volumes:
      - ./client:/home/frontend
    command: ["npm", "run", "dev"]

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: HelloWorld@007
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
